### ISSUE TITLE
Dynamic Variants?

### ISSUE THREAD

**Issue by KemarDarlington** [ankane/field_test#18]
Is it possible to dynamically assign variants to an experiment?

My use case is that our platform has a host of clients that have various landing pages. I would prefer to slug each landing page name under a client. For instance

```
experiments:
  client_a_landing_pages:
    variants:
      - landing_page_a
      - landing_page_b
```

But variants would also be dynamic set via an initializer rather than a YAML file.
