### ISSUE TITLE
Does it make sense to exclude internal devices / IP addresses?

### ISSUE THREAD

**Issue by hwhelchel** [ankane/field_test#19]
I'd like to prevent me and my team's devices from influencing experiment results. Is there a way to do this?

**Comment by ankane** [comment]
Not right now, but we could an option like:

```yml
exclude:
  ips:
    - 127.0.0.1
```

Feel free to submit a PR.
